### numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.2'

### python list的特点

In [4]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# list 对元素类型不做限定
l[2] = 'machine learning'
l

[0, 1, 'machine learning', 3, 4, 5, 6, 7, 8, 9]

In [6]:
import array

In [7]:
arr = array.array('i', [i for i in range(10)])

In [8]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

In [10]:
# array和list都不适合矩阵操作，numpy应运而生

### numpy.array

In [11]:
# np.array 接收list参数创建array
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [13]:
# nparr 只能存储一种类型
nparr.dtype

dtype('int32')

In [14]:
# 隐式转换
nparr[5] = 5.0
nparr.dtype
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

In [18]:
nparr2

array([1., 2., 3.])

In [19]:
# 支持截取表达式
nparr2[:2]

array([1., 2.])

### 其他方式创建numpy.array

In [20]:
# zeros
arr = np.zeros(10)

In [21]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 默认是浮点型
arr.dtype

dtype('float64')

In [24]:
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# 创建矩阵
arr = np.zeros((3,5), dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
# ones 全1矩阵
arr = np.ones(10)

In [28]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
arr.dtype

dtype('float64')

In [31]:
arr = np.ones(10,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
arr = np.ones(shape=(3,5),dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
# 指定数字
arr = np.full(shape=(3,5), fill_value=666)
arr

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange

In [35]:
# 不包含终止点 20
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.arange(0,20,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [37]:
# 步长默认是1
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
# 默认从0开始
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### linspace

In [40]:
# 第三个参数是0-10构成的等差数列, 数列的数量10
# 包含起始点0，和终止点 20
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [41]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [44]:
# 随机生成一个数，前闭后开
np.random.randint(0,20)

19

In [45]:
# 10个元素，每个都是[0,10)
np.random.randint(0,10,10)

array([2, 4, 3, 7, 1, 4, 7, 6, 3, 1])

In [46]:
np.random.randint(4,8,size=10)

array([6, 6, 7, 5, 6, 4, 4, 5, 7, 4])

In [47]:
np.random.randint(4,8,size=(3,5))

array([[7, 7, 6, 7, 5],
       [4, 6, 6, 7, 4],
       [6, 7, 7, 4, 6]])

In [51]:
# 随机种子
np.random.seed(666)

In [52]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [53]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [54]:
# 随机浮点数
np.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [55]:
# 0-1 平均分布的浮点数
np.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

In [57]:
# 正态分布随机
# 均值 10， 方差是100，size默认是1
np.random.normal(10,100)

92.10136919707703

In [58]:
np.random.normal(0,1,size=(3,5))

array([[ 0.36712592,  1.65399586,  0.13946473, -1.21715355, -0.99494737],
       [-1.56448586, -1.62879004,  1.23174866, -0.91360034, -0.27084407],
       [ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021]])

### numpy.array的基本操作

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
X=np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
# 维度
x.ndim

1

In [64]:
# 维度
X.ndim

2

In [65]:
# 每个维度对应的元素个数
x.shape

(10,)

In [66]:
X.shape

(3, 5)

In [67]:
x.size

10

In [68]:
X.size

15

In [69]:
x[0]

0

In [70]:
x[-1]

9

In [71]:
# 不建议使用
X[0][0]

0

In [72]:
X[(0,0)]

0

In [73]:
# 访问多维数组的方式
X[0,0]

0

In [74]:
# 切片
x[0:5]

array([0, 1, 2, 3, 4])

In [75]:
x[:5]

array([0, 1, 2, 3, 4])

In [76]:
x[5:]

array([5, 6, 7, 8, 9])

In [77]:
# 步长
x[::2]

array([0, 2, 4, 6, 8])

In [78]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
# 取前两行的前三列
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [80]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
# 取前两行，每行间隔为2
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [84]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [85]:
# 取第一行
X[0]

array([0, 1, 2, 3, 4])

In [86]:
X[0,:]

array([0, 1, 2, 3, 4])

In [88]:
# 取第一列
X[:, 0]

array([ 0,  5, 10])

In [90]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [91]:
subX[0][0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [92]:
# 考虑效率，numpy的子矩阵和原矩阵其实是同一个
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [97]:
# 如果要变成一个新矩阵，用copy方法
X[0,0]=0
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [98]:
subX[0][0]= 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [99]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape

In [100]:
x.shape

(10,)

In [101]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
# 注意B和x的区别，B的维度为2，x的维度是1

In [107]:
# 指定行数为10，让reshape自己推断列数， -1

x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [109]:
# 只有一行的矩阵
x.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.array合并分割

In [116]:
x= np.array([1,2,3])
y= np.array([3,2,1])
# concatenate 接收列表[]参数
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [118]:
# 按指定轴合并
A = np.array([[1,2,3],[4,5,6]])
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [120]:
# 合并不同维度
np.vstack([A,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [122]:
B = np.full([2,2], 100)
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [123]:
# 分割
x = np.arange(10)

In [124]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
# 两个分割点，3，和 7
np.split(x,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [127]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
# 默认是垂直方向 分成两坨
A1,A2 = np.split(A,2)
print(A1)
print(A2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [131]:
# hsplit 水平方向 分成两坨
A1,A2 = np.hsplit(A,2)
print(A1)
print(A2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### numpy矩阵运算

In [38]:
%%time
A = [i*2 for i in range(1000000)]

Wall time: 134 ms


In [39]:
import numpy as np
L = [i for i in range(1000000)]

In [40]:
n = 1000000
L = np.arange(n)

In [41]:
%%time
A = np.array(2*x for x in L)

Wall time: 17.6 ms


In [42]:
%%time
A = 2 * L

Wall time: 2.93 ms


In [9]:
# numpy array支持所有元素+-*/
n = 10
L = np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X=1/X
X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [13]:
np.abs(X)

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [14]:
np.sin(X)

array([[0.84147098, 0.47942554, 0.3271947 , 0.24740396, 0.19866933],
       [0.16589613, 0.14237173, 0.12467473, 0.11088263, 0.09983342],
       [0.09078392, 0.08323692, 0.07684724, 0.07136785, 0.06661729]])

In [15]:
np.cos(X)

array([[0.54030231, 0.87758256, 0.94495695, 0.96891242, 0.98006658],
       [0.98614323, 0.98981326, 0.99219767, 0.99383351, 0.99500417],
       [0.99587061, 0.99652979, 0.99704288, 0.99745006, 0.9977786 ]])

In [16]:
A = np.array([[1,2],[3,4]])

In [17]:
B = np.array([[5,6],[7,8]])

In [18]:
A+B

array([[ 6,  8],
       [10, 12]])

In [19]:
# 矩阵对应元素相乘
A*B

array([[ 5, 12],
       [21, 32]])

In [20]:
# 矩阵相乘
A.dot(B)

array([[19, 22],
       [43, 50]])

In [37]:
# 转置
A.T

array([[1, 3],
       [2, 4]])

### 向量与矩阵运算

In [44]:
v = np.array([1,2])
v

array([1, 2])

In [46]:
A = np.array([[1,2],[3,4]])

In [47]:
# 向量和矩阵中的每一行做加法
# 自动将低维的元素与高维的每一维的元素进行元素
A+v

array([[2, 4],
       [4, 6]])

In [48]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [50]:
# 向量和矩阵进行运算，会自动判断向量应该取行向量还是列向量
# 这里会自动将v转换成列向量
A.dot(v)

array([ 5, 11])

In [52]:
h = np.array([[1],[2]])

In [53]:
A.dot(h)

array([[ 5],
       [11]])

In [54]:
A.shape

(2, 2)

In [55]:
h.shape

(2, 1)

In [56]:
h.dot(A)

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [57]:
h.shape

(2, 1)

In [58]:
v.shape

(2,)

In [59]:
v

array([1, 2])

In [63]:
A = np.array([[0, 1],
       [2, 3]])

In [64]:
# 矩阵的逆
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [65]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [66]:
# 矩阵的伪逆
# 非方阵
X = np.arange(16).reshape(2,8)
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [67]:
pinvX.shape

(8, 2)

In [68]:
X.shape

(2, 8)

In [70]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [71]:
# 伪逆矩阵*原矩阵 不一定为单位阵
pinvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  3.05311332e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.22044605e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-8.32667268e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952

### 聚合操作

In [5]:
import numpy as np
L = np.random.random(100)

In [6]:
L

array([0.87650473, 0.73915039, 0.23178348, 0.03954821, 0.73467987,
       0.78577723, 0.21700254, 0.48522223, 0.06644235, 0.0087865 ,
       0.03190825, 0.79043167, 0.43381806, 0.66655499, 0.36609415,
       0.32793948, 0.98916194, 0.07383069, 0.26355977, 0.03514344,
       0.66269383, 0.66223579, 0.26629244, 0.21255293, 0.69161493,
       0.53088113, 0.10914208, 0.28113815, 0.48260496, 0.18132208,
       0.87793601, 0.89174766, 0.82440095, 0.01958016, 0.33577298,
       0.42819019, 0.88805994, 0.58243581, 0.08451087, 0.74498347,
       0.15286772, 0.39027974, 0.28601238, 0.37175199, 0.53223245,
       0.62848375, 0.16443863, 0.55522712, 0.16712327, 0.84455197,
       0.39422908, 0.01119841, 0.47647644, 0.9452703 , 0.88805627,
       0.94828637, 0.49275918, 0.9144736 , 0.1685494 , 0.81820548,
       0.92764381, 0.02461327, 0.28895325, 0.00257021, 0.96053406,
       0.6879799 , 0.8220616 , 0.77944351, 0.19601193, 0.07377837,
       0.09704069, 0.40023777, 0.31026317, 0.97619206, 0.75018

In [7]:
sum(L)

45.75273403712415

In [8]:
np.sum(L)

45.752734037124156

In [10]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

62.6 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
204 µs ± 8.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
# 求list的最小值 
np.min(big_array)

3.303978952318154e-06

In [12]:
# 求list的最小值 
np.max(big_array)

0.9999978898439214

In [13]:
big_array.min()

3.303978952318154e-06

In [14]:
big_array.max()

0.9999978898439214

In [16]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.sum(X)

120

In [19]:
# 求某一行的和
# axis = 0 每一列的和，从左往右计算
np.sum(X, axis = 0)

array([24, 28, 32, 36])

In [20]:
# axis = 1 每一行的和，从上往下计算
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

In [22]:
# 所有元素相乘
np.prod(X)

0

In [23]:
# 所有元素加1之后再相乘
np.prod(X + 1)

2004189184

In [24]:
np.mean(X)

7.5

In [25]:
# 中位数
np.median(X)

7.5

In [26]:
# 百分位点的值
np.percentile(big_array, q=50)

0.5015262115754126

In [27]:
# 方差
np.var(big_array)

0.08312651299244703

In [28]:
# 标准差
np.std(big_array)

0.2883166887164998

In [29]:
X = np.random.normal(0,1,size=1000000)

In [31]:
np.mean(X)

0.0008403337660025023

In [32]:
np.std(X)

1.0003283731528294

### 索引

In [33]:
np.min(X)

-4.762801870101464

In [34]:
# 返回最小值的索引
np.argmin(X)

206572

In [35]:
X[206572]

-4.762801870101464

In [36]:
np.argmax(X)

178705

In [37]:
np.max(X)

4.784318236311606

In [38]:
X[178705]

4.784318236311606

### 排序和使用索引

In [39]:
X = np.arange(16)

In [40]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
# 乱序
np.random.shuffle(X)

In [42]:
X

array([ 0,  7, 10,  8, 14,  5,  1,  3, 13,  9,  2,  6, 15, 11, 12,  4])

In [43]:
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
X

array([ 0,  7, 10,  8, 14,  5,  1,  3, 13,  9,  2,  6, 15, 11, 12,  4])

In [45]:
# X本身排序
X.sort()

In [46]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
# 0-10之间随机的 4 * 4矩阵
X = np.random.randint(10, size = (4,4))
X

array([[7, 3, 4, 4],
       [8, 2, 5, 2],
       [7, 8, 7, 1],
       [4, 7, 3, 2]])

In [53]:
# 每一行都排序，默认axis = 1
# axis = 1 是对行操作，不管是求和还是排序，从上往下排序，就是每行排序
np.sort(X)

array([[3, 4, 4, 7],
       [2, 2, 5, 8],
       [1, 7, 7, 8],
       [2, 3, 4, 7]])

In [54]:
np.sort(X, axis = 0)

array([[4, 2, 3, 1],
       [7, 3, 4, 2],
       [7, 7, 5, 2],
       [8, 8, 7, 4]])

In [55]:
X

array([[7, 3, 4, 4],
       [8, 2, 5, 2],
       [7, 8, 7, 1],
       [4, 7, 3, 2]])

In [57]:
X = np.arange(16)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
np.random.shuffle(X)

In [59]:
X

array([ 5, 13,  2, 10,  9, 15, 11,  8,  0,  4,  7, 12,  1,  6, 14,  3])

In [60]:
# 对应的排序之后的元素的原坐标
np.argsort(X)

array([ 8, 12,  2, 15,  9,  0, 13, 10,  7,  4,  3,  6, 11,  1, 14,  5],
      dtype=int64)

In [63]:
# 比3小的元素在左边，比3大的元素在右边
np.partition(X, 3)

array([ 1,  0,  2,  3,  4,  5, 11, 13, 15,  9,  7, 12, 10,  6, 14,  8])

In [64]:
# 同样，返回对应元素的索引
np.argpartition(X, 3)

array([12,  8,  2, 15,  9,  0,  6,  1,  5,  4, 10, 11,  3, 13, 14,  7],
      dtype=int64)

In [66]:
# 按列argsort
X = np.random.randint(10, size = (4,4))
np.argsort(X, axis = 0)

array([[0, 0, 1, 2],
       [3, 1, 3, 3],
       [1, 2, 2, 1],
       [2, 3, 0, 0]], dtype=int64)

In [67]:
np.argpartition(X, 2, axis=1)

array([[1, 0, 3, 2],
       [2, 1, 3, 0],
       [3, 1, 0, 2],
       [0, 3, 2, 1]], dtype=int64)

### Fancy Indexing

In [68]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
# 将索引放在list中，得到相应的元素
inx = [3,5,8]
x[inx]

array([3, 5, 8])

In [71]:
# 按照二维的索引生成相应的二维矩阵
ind = np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [72]:
X = x.reshape(4, -1)

In [73]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
# 取0行，1行，2行对应的1列，2列，3列
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row, col]

array([ 1,  6, 11])

In [76]:
# 第0行的所有列
X[0,col]

array([1, 2, 3])

In [77]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [79]:
# bool数组作为索引
col = [True, False, True, True]
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [80]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [83]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [84]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [85]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [86]:
# x 是一维数组，只有x中为4的元素满足条件
2*x == 24 - x * 4

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [87]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [89]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
np.sum(x <= 2)

3

In [95]:
# 非0元素个数
np.count_nonzero(x <= 1)

2

In [92]:
# 只要任意元素等于0，返回True
np.any(x == 0)

True

In [93]:
np.any(x < 0)

False

In [96]:
np.all(x >= 0)

True

In [97]:
np.all(x>0)

False

In [98]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
# 二维数组操作
# 偶数个数
np.sum(X % 2 == 0)

8

In [102]:
np.sum(X % 2 == 0, axis = 0)

array([4, 0, 4, 0])

In [103]:
# 按行判断是否都大于0
np.all(X > 0, axis = 1)

array([False,  True,  True,  True])

In [104]:
# 大于3 小于10的个数，注意是一个&， 数组和数组与元素
np.sum((x > 3) & (x < 10))

6

In [105]:
np.sum((x % 2 == 0) | (x > 10))

11

In [108]:
np.sum(~(x == 0))

15

In [109]:
# 支持条件表达式
x[x<5]

array([0, 1, 2, 3, 4])

In [110]:
x[x % 2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [114]:
# 二维数组也支持
# X的所有行的最后一个值是否被3整除，满足这个条件的所有列
X[X[:,3] % 3 ==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])