### numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.2'

### python list的特点

In [4]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# list 对元素类型不做限定
l[2] = 'machine learning'
l

[0, 1, 'machine learning', 3, 4, 5, 6, 7, 8, 9]

In [6]:
import array

In [7]:
arr = array.array('i', [i for i in range(10)])

In [8]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

In [10]:
# array和list都不适合矩阵操作，numpy应运而生

### numpy.array

In [11]:
# np.array 接收list参数创建array
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [13]:
# nparr 只能存储一种类型
nparr.dtype

dtype('int32')

In [14]:
# 隐式转换
nparr[5] = 5.0
nparr.dtype
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

In [18]:
nparr2

array([1., 2., 3.])

In [19]:
# 支持截取表达式
nparr2[:2]

array([1., 2.])

### 其他方式创建numpy.array

In [20]:
# zeros
arr = np.zeros(10)

In [21]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 默认是浮点型
arr.dtype

dtype('float64')

In [24]:
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# 创建矩阵
arr = np.zeros((3,5), dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
# ones 全1矩阵
arr = np.ones(10)

In [28]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
arr.dtype

dtype('float64')

In [31]:
arr = np.ones(10,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
arr = np.ones(shape=(3,5),dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
# 指定数字
arr = np.full(shape=(3,5), fill_value=666)
arr

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange

In [35]:
# 不包含终止点 20
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.arange(0,20,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [37]:
# 步长默认是1
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
# 默认从0开始
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### linspace

In [40]:
# 第三个参数是0-10构成的等差数列, 数列的数量10
# 包含起始点0，和终止点 20
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [41]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [44]:
# 随机生成一个数，前闭后开
np.random.randint(0,20)

19

In [45]:
# 10个元素，每个都是[0,10)
np.random.randint(0,10,10)

array([2, 4, 3, 7, 1, 4, 7, 6, 3, 1])

In [46]:
np.random.randint(4,8,size=10)

array([6, 6, 7, 5, 6, 4, 4, 5, 7, 4])

In [47]:
np.random.randint(4,8,size=(3,5))

array([[7, 7, 6, 7, 5],
       [4, 6, 6, 7, 4],
       [6, 7, 7, 4, 6]])

In [51]:
# 随机种子
np.random.seed(666)

In [52]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [53]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [54]:
# 随机浮点数
np.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [55]:
# 0-1 平均分布的浮点数
np.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

In [57]:
# 正态分布随机
# 均值 10， 方差是100，size默认是1
np.random.normal(10,100)

92.10136919707703

In [58]:
np.random.normal(0,1,size=(3,5))

array([[ 0.36712592,  1.65399586,  0.13946473, -1.21715355, -0.99494737],
       [-1.56448586, -1.62879004,  1.23174866, -0.91360034, -0.27084407],
       [ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021]])

### numpy.array的基本操作

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
X=np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
# 维度
x.ndim

1

In [64]:
# 维度
X.ndim

2

In [65]:
# 每个维度对应的元素个数
x.shape

(10,)

In [66]:
X.shape

(3, 5)

In [67]:
x.size

10

In [68]:
X.size

15

In [69]:
x[0]

0

In [70]:
x[-1]

9

In [71]:
# 不建议使用
X[0][0]

0

In [72]:
X[(0,0)]

0

In [73]:
# 访问多维数组的方式
X[0,0]

0

In [74]:
# 切片
x[0:5]

array([0, 1, 2, 3, 4])

In [75]:
x[:5]

array([0, 1, 2, 3, 4])

In [76]:
x[5:]

array([5, 6, 7, 8, 9])

In [77]:
# 步长
x[::2]

array([0, 2, 4, 6, 8])

In [78]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
# 取前两行的前三列
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [80]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
# 取前两行，每行间隔为2
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [84]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [85]:
# 取第一行
X[0]

array([0, 1, 2, 3, 4])

In [86]:
X[0,:]

array([0, 1, 2, 3, 4])

In [88]:
# 取第一列
X[:, 0]

array([ 0,  5, 10])

In [90]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [91]:
subX[0][0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [92]:
# 考虑效率，numpy的子矩阵和原矩阵其实是同一个
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [97]:
# 如果要变成一个新矩阵，用copy方法
X[0,0]=0
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [98]:
subX[0][0]= 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [99]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape

In [100]:
x.shape

(10,)

In [101]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
# 注意B和x的区别，B的维度为2，x的维度是1

In [107]:
# 指定行数为10，让reshape自己推断列数， -1

x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [109]:
# 只有一行的矩阵
x.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.array合并分割

In [116]:
x= np.array([1,2,3])
y= np.array([3,2,1])
# concatenate 接收列表[]参数
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [118]:
# 按指定轴合并
A = np.array([[1,2,3],[4,5,6]])
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [120]:
# 合并不同维度
np.vstack([A,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [122]:
B = np.full([2,2], 100)
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [123]:
# 分割
x = np.arange(10)

In [124]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
# 两个分割点，3，和 7
np.split(x,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [127]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
# 默认是垂直方向 分成两坨
A1,A2 = np.split(A,2)
print(A1)
print(A2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [131]:
# hsplit 水平方向 分成两坨
A1,A2 = np.hsplit(A,2)
print(A1)
print(A2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
